services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: medsignal
      POSTGRES_PASSWORD: medsignal
      POSTGRES_DB: medsignal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medsignal -d medsignal"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://medsignal:medsignal@postgres:5432/medsignal
      ENVIRONMENT: local
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_EXPERIMENT_NAME: medsignal-label-summarization
      SUMMARIZER_MODEL_NAME: sshleifer/distilbart-cnn-6-6
      SUMMARIZER_TASK: summarization
      SUMMARIZER_MAX_INPUT_CHARS: 4000
      SUMMARIZER_MAX_NEW_TOKENS: 180
      SUMMARIZER_MIN_NEW_TOKENS: 60
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      mlflow:
        condition: service_started

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.14.3
    command:
      - mlflow
      - server
      - --host
      - 0.0.0.0
      - --port
      - "5000"
      - --backend-store-uri
      - /mlflow/mlruns
      - --default-artifact-root
      - /mlflow/mlartifacts
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow

  frontend:
    build:
      context: ./frontend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
  mlflow_data:
