services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: medsignal
      POSTGRES_PASSWORD: medsignal
      POSTGRES_DB: medsignal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medsignal -d medsignal"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://medsignal:medsignal@postgres:5432/medsignal
      ENVIRONMENT: local
      SUMMARIZER_MODEL_NAME: sshleifer/distilbart-cnn-6-6
      SUMMARIZER_TASK: summarization
      SUMMARIZER_MAX_INPUT_CHARS: 4000
      SUMMARIZER_MAX_NEW_TOKENS: 180
      SUMMARIZER_MIN_NEW_TOKENS: 60
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
